### ISSUE TITLE
Error compiler

### ISSUE THREAD

**Issue by johnMinelli** [embeddedmz/mailclient-cpp#1]
i tried to use the smtpmail but a simple program give me a linker error: (VS17 W10)

1>ConsoleApplication1.obj : error LNK2001: simbolo esterno "public: __cdecl CSMTPClient::CSMTPClient(class std::function<void __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)>)" (??0CSMTPClient@@QEAA@V?$function@$$A6AXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@std@@@Z) non risolto
1>ConsoleApplication1.obj : error LNK2001: simbolo esterno "public: bool const __cdecl CMailClient::InitSession(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum CMailClient::SettingsFlag const &,enum CMailClient::SslTlsFlag const &)" (?InitSession@CMailClient@@QEAA?B_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00AEBW4SettingsFlag@1@AEBW4SslTlsFlag@1@@Z) non risolto
1>C:\Users\Gio\source\repos\ConsoleApplication1\x64\Release\ConsoleApplication1.exe : fatal error LNK1120: 2 esterni non risolti

I guess i have to build the library and add to the external files to solve it. i wasn't able to do it... could you post a release of the lib? i need it for win x64

**Comment by embeddedmz** [comment]
OK, I ll provide you this weekend with a library built with VS17 and libcurl DLLs.

I have to fix the CMake scripts for Windows, I ll try to do it if I find enough free time. Then you can use CMake-GUI to generate visual studio solutions !

Otherwise, if you need to build libcurl for Windows, this batch script https://github.com/blackrosezy/build-libcurl-windows will allow you to download and build it (I will add it in Readme later), for VS 2017 look at the pull requests.

**Comment by embeddedmz** [comment]
A debug and release of the lib https://file.io/QHBIi9 I also added the DLLs of the latest version of libcurl.

I will post soon a tutorial on how to build the library with CMake-GUI.

Hope that it will work for you.

**Comment by johnMinelli** [comment]
Link not available. Maybe you can post it in the release section, however thanks a lot!!

**Comment by embeddedmz** [comment]
What release section ? Anyway, I tried uploadfiles.io : https://ufile.io/u7jv2

Like said before, I used CMake-gui on Windows (just install the latest version of it), and with it, you can generate a Visual Studio solution of a certain version (e.g. 2017), you have to indicate to it the path of Google Test (can be built with CMake too !) and libcurl (this last can be built with this batch script, it's really easy : https://github.com/ribtoks/build-libcurl-windows).

**Comment by embeddedmz** [comment]
I will update README file and CMake scripts so you can build the library (and the test program) by yourself under Windows for any Visual Studio version, it's a little bit messy but it can be enhanced in future !

On Windows, all the unit tests passed (with my configuration file containing my GMAIL credentials) except for 2 IMAP unit tests : IMAPClientTest.TestGetMailStringSSL and IMAPClientTest.TestGetMailFileSSL, I don't know why,The equivalent tests for POP passed !

**Comment by johnMinelli** [comment]
Okok thanks I'll try it asap

**Comment by embeddedmz** [comment]
I updated the readme file and CMake scripts so you can build the library by yourself !

Under Ubuntu, all the tests are passing (unlike Windows).

In my actual job, I have a Linux project using libraries that, in future, I will need to build under Windows, that's why I wanted to build mailclient-cpp using CMake under Windows to prepare myself.
